import 'es6-string-polyfills';
import 'polyfill-array';
import 'babel-polyfill';
import 'core-js/fn/object/assign';
import 'core-js/fn/array/from';
import 'core-js/fn/array/is-array';
import 'core-js/fn/map';
import 'core-js/fn/set';
import 'core-js/modules/es6.symbol';
